# Do not modify this file!  It was generated by ‘nixos-generate-config’# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  # Kaby Lake Intel 7thGen
  boot.kernelParams = [ "i915.enable_guc=3" ];

  fileSystems."/mnt/WD_Linux" =
    { device = "/dev/disk/by-label/WD_Linux";
      fsType = "auto";
      options = [ "noatime" ];
    }; 

  fileSystems."/mnt/WD_Data" = 
    { device = "/dev/disk/by-label/WD_Data";
      fsType = "auto";
      options = [ "noatime" ];
    };
  
  fileSystems."/mnt/WD_Software" = 
    { device = "/dev/disk/by-label/WD_Software";
      fsType = "auto";
      options = [ "noatime" ];
    };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  # networking.useDHCP = lib.mkDefault true;
  networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  
}
